'use client';
import React, { useRef } from 'react';
import { X, CheckCircle, Printer, Download } from 'lucide-react';
import { useReactToPrint } from 'react-to-print';

const PaymentReceiptModal = ({ isOpen, onClose, data }) => {
  const componentRef = useRef();

  const handlePrint = useReactToPrint({
    contentRef: componentRef, 
    documentTitle: `Receipt_${data?.transactionId || 'Payment'}`,
  });

  if (!isOpen || !data) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-[70] p-4">
      <div className="bg-white rounded-lg shadow-xl max-w-md w-full animate-in fade-in zoom-in-95 duration-200 flex flex-col max-h-[90vh]">
        
        {/* Header */}
        <div className="flex justify-between items-center p-4 border-b border-gray-100">
          <h3 className="text-lg font-semibold text-gray-900">Payment Receipt</h3>
          <button onClick={onClose} className="text-gray-500 hover:text-gray-700">
            <X size={20} />
          </button>
        </div>

        {/* Printable Content */}
        <div ref={componentRef} className="p-6 overflow-y-auto bg-white">
            <div className="flex flex-col items-center mb-6 text-center">
                <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mb-3">
                    <CheckCircle className="text-green-600" size={24} />
                </div>
                <h2 className="text-xl font-bold text-gray-900">Payment Recorded</h2>
                <p className="text-sm text-gray-500 mt-1">
                   {data.status === 'pending' ? 'Pending Verification' : 'Success'}
                </p>
            </div>

            <div className="space-y-4">
                <div className="bg-gray-50 p-4 rounded-lg border border-gray-100">
                    <p className="text-xs text-gray-500 uppercase tracking-wider mb-1">Total Amount</p>
                    <p className="text-3xl font-bold text-gray-900">₹{data.amount}</p>
                </div>

                <div className="grid grid-cols-2 gap-x-4 gap-y-4 text-sm">
                    <div>
                        <p className="text-gray-500 text-xs">Transaction ID</p>
                        <p className="font-medium text-gray-900 break-all">{data.transactionId}</p>
                    </div>
                    <div>
                        <p className="text-gray-500 text-xs">Date</p>
                        <p className="font-medium text-gray-900">{data.paymentDate}</p>
                    </div>
                    <div>
                        <p className="text-gray-500 text-xs">Facility Name</p>
                        <p className="font-medium text-gray-900">{data.userName}</p>
                    </div>
                    <div>
                        <p className="text-gray-500 text-xs">Mobile / Reg #</p>
                        <p className="font-medium text-gray-900">{data.regNumber}</p>
                    </div>
                    <div className="col-span-2">
                        <p className="text-gray-500 text-xs">Plan Duration</p>
                        <p className="font-medium text-gray-900">{data.planType}</p>
                    </div>
                    
                    {data.months && data.months.length > 0 && (
                        <div className="col-span-2">
                            <p className="text-gray-500 text-xs mb-1">Covered Period</p>
                            <div className="flex flex-wrap gap-1">
                                {data.months.map((m, idx) => (
                                    <span key={idx} className="px-2 py-0.5 bg-blue-50 text-blue-700 text-xs rounded border border-blue-100">
                                        {m}
                                    </span>
                                ))}
                            </div>
                        </div>
                    )}
                </div>
            </div>

            {/* Footer Note for Print */}
            <div className="mt-8 pt-4 border-t border-gray-100 text-center hidden print:block">
                <p className="text-xs text-gray-400">Thank you for your payment.</p>
                <p className="text-[10px] text-gray-300 mt-1">Generated by System</p>
            </div>
        </div>

        {/* Actions */}
        <div className="p-4 border-t border-gray-100 flex gap-3 bg-gray-50 rounded-b-lg">
          <button 
            onClick={handlePrint}
            className="flex-1 flex items-center justify-center gap-2 bg-white border border-gray-300 text-gray-700 py-2 rounded-lg hover:bg-gray-50 font-medium transition-colors"
          >
            <Printer size={18} /> Print
          </button>
          <button 
            onClick={onClose}
            className="flex-1 bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 font-medium transition-colors"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
};

export default PaymentReceiptModal;